### ISSUE TITLE
Issue with sidebar/navigation

### ISSUE THREAD

**Issue by BlueTheCircley** [Universal-Omega/MediaWiki-Cosmos-skin#7]
There appear to be strange issues with the sidebar/navigation.

When I decided to change the sidebar/navigation to the most recent one, the sidebar stays the same as the old one, instead of the new one. The sidebar/navigation has the newest ones, yet it ignores the new one on the banner and keeps the old one.
<img width="1417" alt="Screen Shot 2020-09-03 at 9 55 36 AM" src="https://user-images.githubusercontent.com/60414668/92124649-09b21b00-edcc-11ea-837c-1ebaa0692286.png">

**Comment by Universal-Omega** [comment]
That's somewhat interesting, however it's a cached issue. Purging or null editing MediaWiki:Cosmos-navigation should update it, and if it doesn't, copy the sidebar to MediaWiki:Cosmos-navigation.

**Comment by Universal-Omega** [comment]
> Even if I reset the cache, purge, replacing content on MediaWiki:Cosmos-navigation with -, and even coping the sidebar to MediaWikI:Cosmos-navigation, it still uses the old sidebar.

Well then, thanks for the report. I will look into CosmosNavigation (https://github.com/Universal-Omega/MediaWiki-Cosmos-skin/blob/REL1_34/includes/CosmosNavigation.php) today.

**Comment by Universal-Omega** [comment]
https://github.com/Universal-Omega/MediaWiki-Cosmos-skin/commit/888eeaf245de2525acbf07c90b8cd2503ddf6f1a#diff-2862006f96b3b53e390d50cfe762ec8a

**Comment by BlueTheCircley** [comment]
Looks like there's a change for the code. I restarted the cache on Browser, and I still don't see the sidebar change.

**Comment by Universal-Omega** [comment]
> Looks like there's a change for the code. I restarted the cache on Browser, and I still don't see the sidebar change.

Do you use Miraheze? If so, I'm pushing the changes there right now.

**Comment by BlueTheCircley** [comment]
Yes I used Miraheze.

**Comment by Universal-Omega** [comment]
> Yes I used Miraheze.

Alright, changes there should take effect within next 10 minutes. If then, the navigation still doesn't update, let me know please.

**Comment by Universal-Omega** [comment]
Does it now work for you?

**Comment by BlueTheCircley** [comment]
Yes! It's doing good!

**Comment by Universal-Omega** [comment]
> Yes! It's doing good!

Great!
